const languageMap: Record<string, string> = {
  ab: "Abkhazian",
  aa: "Afar",
  af: "Afrikaans",
  sq: "Albanian",
  am: "Amharic",
  ar: "Arabic",
  an: "Aragonese",
  hy: "Armenian",
  as: "Assamese",
  ay: "Aymara",
  az: "Azerbaijani",
  ba: "Bashkir",
  eu: "Basque",
  bn: "Bengali (Bangla)",
  dz: "Bhutani",
  bh: "Bihari",
  bi: "Bislama",
  br: "Breton",
  bg: "Bulgarian",
  my: "Burmese",
  be: "Byelorussian (Belarusian)",
  km: "Campuchia",
  ca: "Catalan",
  zh: "Tiếng Trung Quốc",
  "zh-Hans": "Tiếng Trung Quốc (Giản thể)",
  "zh-Hant": "Tiếng Trung Quốc (Phồn thể)",
  co: "Corsican",
  hr: "Croatian",
  cs: "Séc",
  da: "Tiếng Đan Mạch",
  nl: "Tiếng Hà Lan",
  en: "Tiếng Anh",
  eo: "Esperanto",
  et: "Estonian",
  fo: "Faeroese",
  fa: "Farsi",
  fj: "Fiji",
  fi: "Tiếng Phần Lan",
  fr: "Tiếng Pháp",
  fy: "Frisian",
  gl: "Galician",
  gd: "Gaelic (Scottish)",
  gv: "Gaelic (Manx)",
  ka: "Georgian",
  de: "Tiếng Đức",
  el: "Tiếng Hy Lạp",
  kl: "Greenlandic",
  gn: "Guarani",
  gu: "Gujarati",
  ht: "Haitian Creole",
  ha: "Hausa",
  he: "Hebrew",
  iw: "Hebrew",
  hi: "Hindi",
  hu: "Hungarian",
  is: "Icelandic",
  io: "Ido",
  id: "Tiếng Indonesia",
  in: "Tiếng Indonesia",
  ia: "Interlingua",
  ie: "Interlingue",
  iu: "Inuktitut",
  ik: "Inupiak",
  ga: "Irish",
  it: "Tiếng Ý",
  ja: "Tiếng Nhật",
  jv: "Javanese",
  kn: "Kannada",
  ks: "Kashmiri",
  kk: "Kazakh",
  rw: "Kinyarwanda (Ruanda)",
  ky: "Kirghiz",
  rn: "Kirundi (Rundi)",
  ko: "Tiếng Hàn Quốc",
  ku: "Kurdish",
  lo: "Tiếng Lào",
  la: "Latin",
  lv: "Latvian (Lettish)",
  li: "Limburgish (Limburger)",
  ln: "Lingala",
  lt: "Lithuanian",
  mk: "Macedonian",
  mg: "Malagasy",
  ms: "Malay",
  ml: "Malayalam",
  mt: "Maltese",
  mi: "Maori",
  mr: "Marathi",
  mo: "Moldavian",
  mn: "Mongolian",
  na: "Nauru",
  ne: "Tiếng Nepal",
  no: "Norwegian",
  oc: "Occitan",
  or: "Oriya",
  om: "Oromo (Afaan Oromo)",
  ps: "Pashto (Pushto)",
  pl: "Polish",
  pt: "Tiếng Bồ Đào Nha",
  pa: "Punjabi",
  qu: "Quechua",
  rm: "Rhaeto-Romance",
  ro: "Romanian",
  ru: "Tiếng Nga",
  sm: "Samoan",
  sg: "Sangro",
  sa: "Sanskrit",
  sr: "Serbian",
  sh: "Serbo-Croatian",
  st: "Sesotho",
  tn: "Setswana",
  sn: "Shona",
  ii: "Sichuan Yi",
  sd: "Sindhi",
  si: "Sinhalese",
  ss: "Siswati",
  sk: "Slovak",
  sl: "Slovenian",
  so: "Somali",
  es: "Tiếng Tây Ban Nha",
  su: "Sundanese",
  sw: "Swahili (Kiswahili)",
  sv: "Tiếng Thụy Điển",
  tl: "Tagalog",
  tg: "Tajik",
  ta: "Tamil",
  tt: "Tatar",
  te: "Telugu",
  th: "Tiếng Thái Lan",
  bo: "Tibetan",
  ti: "Tigrinya",
  to: "Tonga",
  ts: "Tsonga",
  tr: "Tiếng Thổ Nhĩ Kỳ",
  tk: "Turkmen",
  tw: "Twi",
  ug: "Uighur",
  uk: "Ukrainian",
  ur: "Urdu",
  uz: "Uzbek",
  vi: "Tiếng Việt Nam",
  vo: "Volapük",
  wa: "Wallon",
  cy: "Welsh",
  wo: "Wolof",
  xh: "Xhosa",
  yi: "Yiddish",
  ji: "Yiddish",
  yo: "Yoruba",
  zu: "Zulu",
};

export function getCountryDisplay(code: string): string {
  const name = languageMap[code.toLowerCase()] || code;
  return name;
}